In [4]:
import sys
sys.path.append("..")

from forwardKinematics import robot_config
import numpy as np
import time

pi = np.pi
myRobot = robot_config()

In [ ]:
q = np.array([0.5, 0.25, 0., 0., 0., 0., 0.])
print("Joint angles/positions {}".format(q))

s = time.time()
for i in range(1000):
	positions = myRobot.forwardKinPos(q)
dt = time.time()-s
print(dt/1000)
print('Forward kinematic positions: {}'.format(positions))

s = time.time()
for i in range(100):
	orientation = myRobot.forwardKinOrientation(q)
dt = time.time()-s
print(dt/100)
print('Forward kinematic orientations: {}'.format(orientation))

Joint angles/positions [0.5  0.25 0.   0.   0.   0.   0.  ]
Generating transform function for j1
Generating transform function for j2
Generating transform function for j3
Generating transform function for j4
Generating transform function for j5
Generating transform function for j6
Generating transform function for j7
0.0039105889797210695
Forward kinematic positions: [[ 0.00000000e+00  5.00000000e-01  3.06161700e-17]
 [-2.50000000e-01  5.00000000e-01  6.12323400e-17]
 [-2.05000000e+00  5.00000000e-01  2.81668764e-16]
 [-2.16300000e+00  5.00000000e-01  2.95507273e-16]
 [-2.24300000e+00  5.00000000e-01  3.10203034e-16]
 [-2.32300000e+00  5.00000000e-01  3.24898796e-16]
 [-2.49800000e+00  5.00000000e-01  2.30000000e-02]]
Generating transform function for j1
Generating transform function for j2
Generating transform function for j3
Generating transform function for j4
Generating transform function for j5
Generating transform function for j6


In [3]:

# calculate position of the end-effector
#xyz = myRobot.Tx('EE', q)
#print('XYZ forward kin: {}'.format(xyz))
#print(xyz.shape)
#print(type(xyz))
# calculate the Jacobian for the end effector
s = time.time()
for i in range(1000):
	JEE = myRobot.J('j4', q)
dt = time.time()-s
print(dt/1000)
print("analytic jacobian: \n{}".format(JEE))

def calculateJacobian(q, num_joints = 7, dx = 1e-5):
	jacobian = np.zeros((6,num_joints))
	for i in range(num_joints):
		q_plus = q.copy()
		q_plus[i] += dx
		q_minus = q.copy()
		q_minus[i] -= dx
		x_plus = myRobot.Tx('EE', q_plus)
		x_minus = myRobot.Tx('EE', q_minus)
		jacobian[:3, i] = (x_plus - x_minus) / (2*dx)

		qEE_plus = myRobot.Te('EE', q_plus)
		qEE_minus = myRobot.Te('EE', q_minus)
		jacobian[3:, i] = (qEE_plus - qEE_minus) / (2*dx)

	return jacobian

s = time.time()
for i in range(1000):
	JEE_numerical = calculateJacobian(q)
dt = time.time()-s
print(dt/1000)
print("numeric jacobian: \n{}".format(JEE_numerical))



#J_orientation = myRobot._calc_T('j1', lambdify = True)
#print(J_orientation(*tuple(q)))

s = time.time()
for i in range(1000):
	orientation = myRobot.forwardKinOrientation(q)
dt = time.time()-s
print(dt/1000)
print('Forward kinematic orientations: {}'.format(orientation))

s = time.time()
for i in range(1000):
	test = myRobot.forwardKinHomogenous(q)
dt = time.time()-s
print(dt/1000)

Generating Jacobian function for j4
0.00024085140228271483
analytic jacobian: 
[[ 0.0000000e+00 -1.0000000e+00  0.0000000e+00 -0.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 1.0000000e+00  6.1232340e-17  0.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 6.1232340e-17  1.2246468e-16  0.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00 -1.0000000e+00 -1.0000000e+00 -6.1232340e-17
   0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 1.0000000e+00  6.1232340e-17  6.1232340e-17 -1.0000000e+00
   0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 6.1232340e-17  1.2246468e-16  1.2246468e-16 -1.2246468e-16
   0.0000000e+00  0.0000000e+00  0.0000000e+00]]
Generating transform function for EE
Generating transform function for EE
0.051677149772644045
numeric jacobian: 
[[ 0.00000000e+00 -1.00000000e+00  0.00000000e+00 -2.30000000e-02
   0.00000000e+00 -2.30000000e-02 -1.00000000e+00]
 [ 1.00000000e+00  0.00000000