In [1]:
#puts above directory into the path
import sys
sys.path.append("../../VREP_robot")
sys.path.append("../../VREP_robot/utils")
sys.path.append("../")
import vrep
from vrepRobot import *

from forwardKinematics import robot_config
import numpy as np
import time

pi = np.pi

In [2]:
myRobot = robot_config()
vrep_env = VREP_Environement()
robot_handles  = ['pose_j0', 'pose_j1', 'pose_j2', 'pose_j3', 'pose_j4', 'pose_j5', 'pose_j6', 'pose_j7']
vrep_env.add_robot(VREP_Robot('robot', robot_handles))
vrep_env.start_simulation()

Connected to remote API server
1 robot(s) connected: ['robot']


In [3]:
start = time.time()

while time.time() - start < 18:
    dt = time.time() - start
    a = np.sin(dt)*0.5
    q = np.array([0.2, -2.5, 0., 0., 0., 0., 0. + a])
    positions = np.zeros((8,3))
    positions[1:,:] = (myRobot.forwardKinPos(q))
    orientations = np.zeros((8, 4)) #4 for quat
    orientations[0,-1] = 1

    print('Forward kinematic positions: {}'.format(positions))
    orientations[1:,:] = myRobot.forwardKinOrientation(q)
    print('Forward kinematic orientations: {}'.format(orientations))

    print(vrep_env.robot.handle_names)
    for i in range(len(robot_handles)):
        vrep_env.robot.setObjectPosition(vrep_env.robot.handles[i], positions[i])
        vrep_env.robot.setObjectQuaternion(vrep_env.robot.handles[i], orientations[i])
        
    time.sleep(0.2)

Generating transform function for j1
Generating transform function for j2
Generating transform function for j3
Generating transform function for j4
Generating transform function for j5
Generating transform function for j6
Generating transform function for j7
Forward kinematic positions: [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  2.00000000e-01  1.22464680e-17]
 [ 2.50000000e+00  2.00000000e-01 -2.93915232e-16]
 [ 7.00000000e-01  2.00000000e-01 -7.34788079e-17]
 [ 5.87000000e-01  2.00000000e-01 -5.96402991e-17]
 [ 5.07000000e-01  2.00000000e-01 -4.49445375e-17]
 [ 4.27000000e-01  2.00000000e-01 -3.02487759e-17]
 [ 2.51946594e-01  2.00000000e-01  2.30000000e-02]]
Generating transform function for j1
Generating transform function for j2
Generating transform function for j3
Generating transform function for j4
Generating transform function for j5
Generating transform function for j6
Generating transform function for j7
Forward kinematic orientations: [[ 0.0000000

Forward kinematic positions: [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  2.00000000e-01  1.22464680e-17]
 [ 2.50000000e+00  2.00000000e-01 -2.93915232e-16]
 [ 7.00000000e-01  2.00000000e-01 -7.34788079e-17]
 [ 5.87000000e-01  2.00000000e-01 -5.96402991e-17]
 [ 5.07000000e-01  2.00000000e-01 -4.49445375e-17]
 [ 4.27000000e-01  2.00000000e-01 -3.02487759e-17]
 [ 1.19247956e-01  2.00000000e-01  2.30000000e-02]]
Forward kinematic orientations: [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00 -7.07106781e-01 -7.07106781e-01  4.32978028e-17]
 [ 5.00000000e-01 -5.00000000e-01 -5.00000000e-01  5.00000000e-01]
 [ 5.00000000e-01 -5.00000000e-01 -5.00000000e-01  5.00000000e-01]
 [ 5.00000000e-01 -5.00000000e-01  5.00000000e-01  5.00000000e-01]
 [ 1.66533454e-16 -2.22044605e-16  7.07106781e-01  7.07106781e-01]
 [ 5.00000000e-01 -5.00000000e-01  5.00000000e-01  5.00000000e-01]
 [ 0.00000000e+00 -7.07106781e-01 -4.32978028e-17  7.07106781

KeyboardInterrupt: 

In [7]:
#JEE = myRobot.J('EE', q)
#print("analytic jacobian: \n{}".format(JEE))

In [3]:
vrep_env.robot.getCollisionHandle('Collision')

In [5]:
print(vrep_env.robot.getCollisionState())

False
