In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time

import sys
sys.path.append("..")
from generateTrajectory import *
from armControl import *
from forwardKinematics import robot_config
from utils.motor_setup import Motors
import signal

In [2]:
pi = np.pi
armKinematics = robot_config()
q = np.array([0., 0., 0., 0., 0., 0., 0.])
positions = armKinematics.forwardKinPos(q)
orientation = armKinematics.forwardKinOrientation(q)

armController = remoteRobotArm()
armController.initMotorArmMixing()


def signal_handler(signal, frame):
    motors.tcp_close()
signal.signal(signal.SIGINT, signal_handler)
#script_dir = os.path.dirname(__file__)
#results_dir = os.path.join(script_dir, 'Current_data/')
#if not os.path.isdir(results_dir):
#os.makedirs(results_dir)
#Constants
socket_ip = '192.168.1.20'
socket_port = 1122
P = 0
PL = 0
I = 0
IL = 0
D = 0
motors = Motors(P ,PL ,I, IL ,D)

Generating transform function for j1
Generating transform function for j2
Generating transform function for j3
Generating transform function for j4
Generating transform function for j5
Generating transform function for j6
Generating transform function for j7
Generating transform function for j1
Generating transform function for j2
Generating transform function for j3
Generating transform function for j4
Generating transform function for j5
Generating transform function for j6
Generating transform function for j7


In [51]:
motors.tcp_init(socket_ip, socket_port)
print("Arming motors now...")
motors.arm_motors()

Opening socket at ip: 192.168.1.20 using port: 1122
Arming motors now...
initializing motors to [0 0 0 0 0 0 0 0]
*** C side has an error or needs to be armed ***

Arming motors


In [84]:
q = np.array([0, 0, 0, 0, 0, 0, 0])
armController.jointAngleSetpoint = q
armController.updateMotorArmMixing()
print(armController.motorAngleSetpoint)
encoderCounts = armController.motorAngleSetpoint * 479 * 1440 / (2 * pi)
encoderCounts = encoderCounts.astype(int)
encoderCounts[4] = -1 * encoderCounts[4]
encoderCounts[5] = -1 * encoderCounts[5]

print(encoderCounts)

[0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0]


In [85]:
enc_position = np.zeros(8)
enc_position[1:] = encoderCounts
print(enc_position)
motors.command_motors(enc_position)
time.sleep(1)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [50]:
motors.tcp_close()